## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則化來觀察訓練情形。

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
## Regression

boston = datasets.load_boston()

x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size = 0.33, random_state = 10)

regr = linear_model.LinearRegression()

regr.fit(x_train,y_train)

y_pred = regr.predict(x_test)

In [3]:
regr.coef_

array([-1.56353750e-01,  6.60616548e-02, -2.01655290e-02,  1.57889806e+00,
       -1.53490777e+01,  3.34105533e+00,  1.14773954e-02, -1.55360652e+00,
        3.05450100e-01, -1.21583833e-02, -8.14405729e-01,  1.32763069e-02,
       -5.45290138e-01])

In [4]:
print("Mean squared error: %.2f" % mean_squared_error(y_test,y_pred))

Mean squared error: 27.10


In [17]:
## Lasso

boston = datasets.load_boston()

x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size = 0.33, random_state = 10)

lasso = linear_model.Lasso(alpha = 1.0)

lasso.fit(x_train,y_train)

y_pred = lasso.predict(x_test)

In [18]:
lasso.coef_

array([-0.10475563,  0.07649297, -0.01718277,  0.        , -0.        ,
        0.24993515,  0.03023573, -0.80122944,  0.26755925, -0.01537057,
       -0.58410577,  0.01011944, -0.76343344])

In [19]:
print("Mean squared error: %.2f" % mean_squared_error(y_test,y_pred))

Mean squared error: 36.11


In [20]:
## Ridge

boston = datasets.load_boston()

x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size = 0.33, random_state = 10)

ridge = linear_model.Ridge(alpha = 1.0)

ridge.fit(x_train,y_train)

y_pred = ridge.predict(x_test)

In [21]:
ridge.coef_

array([-1.52632064e-01,  6.72194813e-02, -4.61868347e-02,  1.45844821e+00,
       -7.76898482e+00,  3.39133018e+00,  4.68041987e-03, -1.43319434e+00,
        2.87697853e-01, -1.27154968e-02, -7.34594385e-01,  1.36842091e-02,
       -5.54979507e-01])

In [22]:
print("Mean squared error: %.2f" % mean_squared_error(y_test,y_pred))

Mean squared error: 27.64
